### ISSUE TITLE
Please include a screen shot in the readme

### ISSUE THREAD

**Issue by unixorn** [jakshin/yazpt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by jakshin** [comment]
Hey there! I recently switched from bash to zsh as my primary shell, and awesome-zsh-plugins was a valuable resource for me during that transition, so thank you for that - I appreciate the time and effort you put into maintaining it.

I'd love to have yazpt listed on awesome-zsh-plugins, but most of the things I'd want to capture in screen shots aren't actually implemented yet. ;-) What it does, it does well enough, but it isn't yet at all customizable. I plan to make it more interesting over the next week or two, then beef up the readme. I'll include screenshots then.

**Comment by unixorn** [comment]
Ok. When you're at a point where you think it's ready for other people to use, either comment on this issue or PR it onto https://github.com/unixorn/awesome-zsh-plugins.

**Comment by jakshin** [comment]
I've (finally) gotten yazpt far enough along that I feel like it's worth folks paying a bit of attention to, and added some screenshots to the readme. :)

I've opened a PR: https://github.com/unixorn/awesome-zsh-plugins/pull/932
